// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-8DV-QcPSK2p_h9Ak0GgWy-UzqTTujY4',
    appId: '1:122806099592:web:ba687dcf9f38d2cfa8093d',
    messagingSenderId: '122806099592',
    projectId: 'cloth-project-d9ffb',
    authDomain: 'cloth-project-d9ffb.firebaseapp.com',
    storageBucket: 'cloth-project-d9ffb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxHm5wQR5QMpxJasm-5M7lxocw-CvBFwQ',
    appId: '1:122806099592:android:104d06d674137095a8093d',
    messagingSenderId: '122806099592',
    projectId: 'cloth-project-d9ffb',
    storageBucket: 'cloth-project-d9ffb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0szIZZ8Y61NcZYLR-bRkkLOHCJ6Six0A',
    appId: '1:122806099592:ios:fff2ad575e156476a8093d',
    messagingSenderId: '122806099592',
    projectId: 'cloth-project-d9ffb',
    storageBucket: 'cloth-project-d9ffb.firebasestorage.app',
    iosBundleId: 'com.example.rangmahal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0szIZZ8Y61NcZYLR-bRkkLOHCJ6Six0A',
    appId: '1:122806099592:ios:fff2ad575e156476a8093d',
    messagingSenderId: '122806099592',
    projectId: 'cloth-project-d9ffb',
    storageBucket: 'cloth-project-d9ffb.firebasestorage.app',
    iosBundleId: 'com.example.rangmahal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-8DV-QcPSK2p_h9Ak0GgWy-UzqTTujY4',
    appId: '1:122806099592:web:afcfd9143dce8f72a8093d',
    messagingSenderId: '122806099592',
    projectId: 'cloth-project-d9ffb',
    authDomain: 'cloth-project-d9ffb.firebaseapp.com',
    storageBucket: 'cloth-project-d9ffb.firebasestorage.app',
  );
}
